language: python

branches:
  except:
  - gh-pages

stages:
- test
- name: deploy
  if: tag IS present

jobs:
  include:
  - python: 3.6
    env: TOXENV=unit_py3_6,check,doc
  - python: 2.7
    env: TOXENV=unit_py2_7,check,doc
  - stage: deploy
    python: 3.6
    env: TOXENV=doc_travis
    deploy:
      - provider: pages
        skip_cleanup: true
        local-dir: doc/build/html
        github-token:
          secure: H6gF9STlXtiCvmIkBgbuCLY0ovkjvRX69OfaliKdhvmysHfFTiHn6rx2keGmd0kdEhGj12YgNEVwAd9qEEZonFfmqEzNNSW5+nIEvVjGZ9b8FnnwSGX/y2XBldIDNu+imuhkxzzFlylbMABJSvJy8W6dwuic2DBdiVAsb8e9fUHnvbTTice76DyuHCDjM7EGt34K3xP8sjwMm3dPKvO2s+Ij3u+j5TE/aovxoaY5oRO8fp2j7lbTUXIQb4P4mysro22K4rgWng83/IVaIAT0nFlX24WltraUxIzW/MJe8SYXaDSbgyzMpOtUxlKs+5/wAAdEBoE8aMTBwOF0f5eQJHTguL2oCy+7VELtMVq8oUeHzyRh7JcBAE7Hd3WgWrWrZCfIxEZ8pAEwLb3SJUnegb7z0PRBnHDNbwLcsxzKKupMVJ1eCJmlowJUea5ODW3ruizhvg9S3pBQOUwmQqvj2TS2byXa4zToqOzxcrMMWK0v667eO9XKAFkhNdA6Vr7XuwTbIMt/+dSQUH3VwxNK2Hpbe7EEf9Kh8K2L1U2UnrfpHmcm+8Fd1aYA0UsvVNhFF/MvDBBoHguvmAbw/x5rrbbNYW1Q+pUkYj/UTvrI/GU7w1h421R4VMigIkI7u6Yq5cVBYT95SzNPb6Bt2rKTAr6RpcqRwZV5AB7oL2Flgak=
        keep-history: true
        on:
          tags: true
      - provider: pypi
        skip_cleanup: true
        user: schaefi
        password:
          secure: UhNSSiqZ5ecVYW4wLibg6rsWySO+69mgQyYkvTQcIMwlBWMzfqsj48iRZBpWZJhJaPfGgsJ8HwC8ImexTa58ZRPep5pxTlVIVZ8gKldRzoQ/Wn+UTeEGgfXvYIbQel9jWIu5MLs13R3oUbTjO8ZXtYuWgjVDUCMGnI7ffvXf7HCvBydBdOIDSl82PZTJSSxUU1LQlSnMgbmWpf4ho2QhdQw7E3eRN/kFujGFTtbIVti6qpIMR2HvS2zI7z1KOe085s8570ytvSVCDApdHyIsPuP9gSZ5R807CrjnJqGOVckA+nheN2nMBRzlLOvZTMbPp5s/gIArFxd0UfFhmU2bxAvo/WCN9XdN9ZQZXJUx/fbZh/dmO7oU+KK9CdwfGZ4vJAzDPaccKvSxl/SWeWDpYcsrh2Q/t+xbq5nA+Rllecc1lavVi/MtKbLQIazGLGCEHNV18KSE24O8u1lyPjRCzq6G5D3Dda1vyWh/0gvw4HC9xoj944qWdGY/zxeYacXJHwB4PqgiQAX1zfSPPH/s0MMI9ZiQpHzTHrQx3lj+aERsu2VFPW93y7eNooA6+vny6JxO67krs9PhlBOoB8rrK9Yxu5LbHxLBYfbl/xhrs9ZxQRG1hzNQq4PZYYzdBjdbSf3dz24V2D86hkXUYOJqQh20fZ53s5qcpxNgnj9uZco=
        distributions: sdist
        on:
          tags: true

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y git
- sudo apt-get install -y xsltproc
- sudo apt-get install -y genisoimage
- sudo apt-get install -y enchant
- sudo apt-get install -y shellcheck

install:
- pip install --upgrade pip
- pip install tox

script:
- tox
