name: CI-Compliant-To-Kiwi-9
on:
  pull_request:
    branches: [main]

jobs:
  compliance_test:
    if: ${{ github.repository == 'OSInside/kiwi' }}
    name: Capable for Rebase to kiwi v9.x.x
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run rebase
        run: helper/v9compliance_test.sh "${GITHUB_HEAD_REF}"
